Services:
  core-bookstack-app: # Project Documentation Frontend 
    image: lscr.io/linuxserver/bookstack:latest
    container_name: core-bookstack-app
    hostname: core-bookStack-app
    network_mode: "bridge"
    dns:
      - ${DNS1}
      - ${DNS2}
      - ${DNS3}
      - ${DNS4}
    depends_on:
      - core-bookstack-db
    env_file:
      - stack.env
    environment:
      - PUID: ${BOOKSTACK-PUID}
      - PGID: ${BOOKSTACK-PGID}
      - TZ=America/Denver
      - APP_URL=https://${BOOKSTACK_DOMAIN}
      - APP_KEY=${BOOKSTACK_APP_KEY}
      - DB_HOST=BookStack-DB
      - DB_PORT=3306
      - DB_USERNAME=bookstack
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=bookstack
      - SESSION_SECURE_COOKIE=true
    ports:
      - 3004:80
    restart: unless-stopped
    volumes: 
      - ${volumeroot}/core/bookstack/app:/config:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      
  core-bookstack-db: # Project Documentation Frontend
    image: mariadb:10.5
    container_name: core-bookstack-db
    hostname: core-bookstack-db
    network_mode: "bridge"
    dns:
      - ${DNS1}
      - ${DNS2}
      - ${DNS3}
      - ${DNS4}
    env_file:
      - stack.env 
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - ${volumeroot}/core/bookstack/db/mariadb:/var/lib/mysql:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
  core-docker-socket-proxy:
    image: linuxserver/docker-socket-proxy:latest
    container_name: core-docker-socket-proxy
    hostname: core-docker-socket-proxy
    network_mode: "bridge"
    dns:
      - ${DNS1}
      - ${DNS2}
      - ${DNS3}
      - ${DNS4}
    environment:
      - PUID: ${DOCKERSOCKETPROXY-PUID}
      - PGID: ${DOCKERSOCKETPROXY-PGID}
      - TZ: 'America/Denver'
    ports:
      - '2375:2375'  # exposes proxy on host port 2375
    restart: unless-stopped
    volumes:
      - ${volumeroot}/core/docker-socket-proxy/config:/config:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

  core-filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: core-filebrowser
    hostname: core-filebrowser
    environment:
      - PUID: ${FILEBROWSER-PUID}
      - PGID: ${FILEBROWSER-PGID}
    ports:
      - 3001:80
    restart: unless-stopped
    volumes:
      - ${VOLUMEROOT}:/srv:rw
      - ${VOLUMEROOT}/core-filebrowser/filebrowser.db:/database.db:rw      
      - ${VOLUMEROOT}/core-filebrowser/settings.json:/config.json:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
  core-glanceapp:
    image: glanceapp/glance
    container_name: core-glanceapp
    hostname: core-glanceapp
    network_mode: "bridge"
    dns:
      - ${DNS1}
      - ${DNS2}
      - ${DNS3}
      - ${DNS4}
    env_file:
      - stack.env
    ports:
      - 3004:8080
    restart: unless-stopped
    volumes:
      - ${VOLUMEROOT}/core-glanceapp/assets:/app/assets:rw
      - ${VOLUMEROOT}/core-glanceapp:/app/config:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      
  core-homepage: # Project Internal Dashboard
    image: ghcr.io/gethomepage/homepage:latest
    container_name: core-homepage
    hostname: core-homepage
    network_mode: "bridge"
    dns:
      - ${DNS1}
      - ${DNS2}
      - ${DNS3}
      - ${DNS4}
    environment:
      - PUID: ${HOMEPAGE-PUID}
      - PGID: ${HOMEPAGE-PGID}
      - HOMEPAGE_ALLOWED_HOSTS=${HomepageFQDNs}
      - TZ=America/Denver
    network_mode: "bridge"
    ports:
      - 3000:3000
    restart: unless-stopped      
    volumes:
      - ${VOLUMEROOT}/core/homepage/config:/app/config:rw 
      - ${VOLUMEROOT}/core/homepage/images:/app/public/images:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
  core-portainer_agent:
    image: portainer/agent:latest
    container_name: core-portainer_agent
    hostname: core-portainer_agent
    network_mode: "bridge"
    dns:
      - ${DNS1}
      - ${DNS2}
      - ${DNS3}
      - ${DNS4}
    ports:
      - 9001:9001
    environment:
      - PUID: ${PORTAINERAGENT-PUID}
      - PGID: ${PORTAINERAGENT-PGID}
      - TZ=America/Denver
    restart: unless-stopped
    volumes:
      - ${VOLUMEROOT}:/var/lib/docker/volumes:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
  core-webmin:
    image: webdevops/webmin:latest
    container_name: core-webmin
    hostname: core-webmin
    network_mode: "bridge"
    dns:
      - ${DNS1}
      - ${DNS2}
      - ${DNS3}
      - ${DNS4}
    ports:
      - 10000:10000 
    environment:
      - ROOT_PASSWORD=${WEBMINPASSWORD}
    volumes:
      - ${VOLUMEROOT}/webmin:/etc/webmin
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    restart: unless-stopped
